package com.test.TestSNSLambdaEvent.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="TestData")
public class TestData implements Serializable {

private static final long serialVersionUID = 1409811442961495294L;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	protected String id;
	
	@DynamoDBAttribute
	protected String strVal;
	
	public TestData() {
		super();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStrVal() {
		return strVal;
	}

	public void setStrVal(String strVal) {
		this.strVal = strVal;
	}
	
}
